// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_A_matrix_cpp
arma::mat calc_A_matrix_cpp(const arma::mat& G);
RcppExport SEXP _CompGEBLUP_calc_A_matrix_cpp(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_A_matrix_cpp(G));
    return rcpp_result_gen;
END_RCPP
}
// calc_D_matrix_cpp
arma::mat calc_D_matrix_cpp(const arma::mat& G);
RcppExport SEXP _CompGEBLUP_calc_D_matrix_cpp(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_D_matrix_cpp(G));
    return rcpp_result_gen;
END_RCPP
}
// calc_epistatic_matrix_cpp
arma::mat calc_epistatic_matrix_cpp(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _CompGEBLUP_calc_epistatic_matrix_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_epistatic_matrix_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// eigen_decomp_cpp
Rcpp::List eigen_decomp_cpp(const arma::mat& K);
RcppExport SEXP _CompGEBLUP_eigen_decomp_cpp(SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_decomp_cpp(K));
    return rcpp_result_gen;
END_RCPP
}
// emma_reml_loglik_cpp
double emma_reml_loglik_cpp(const arma::vec& eta, const arma::mat& xi, const arma::vec& d, double lambda);
RcppExport SEXP _CompGEBLUP_emma_reml_loglik_cpp(SEXP etaSEXP, SEXP xiSEXP, SEXP dSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(emma_reml_loglik_cpp(eta, xi, d, lambda));
    return rcpp_result_gen;
END_RCPP
}
// emma_reml_cpp
Rcpp::List emma_reml_cpp(const arma::vec& y, const arma::mat& X, const arma::mat& K, double tol, int max_iter);
RcppExport SEXP _CompGEBLUP_emma_reml_cpp(SEXP ySEXP, SEXP XSEXP, SEXP KSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(emma_reml_cpp(y, X, K, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// gwas_emmax_cpp
arma::mat gwas_emmax_cpp(const arma::vec& y, const arma::mat& X, const arma::mat& M, const arma::mat& U, const arma::vec& d, double lambda);
RcppExport SEXP _CompGEBLUP_gwas_emmax_cpp(SEXP ySEXP, SEXP XSEXP, SEXP MSEXP, SEXP USEXP, SEXP dSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(gwas_emmax_cpp(y, X, M, U, d, lambda));
    return rcpp_result_gen;
END_RCPP
}
// create_Z_sparse_cpp
arma::sp_mat create_Z_sparse_cpp(const arma::uvec& factor_idx, int n_levels);
RcppExport SEXP _CompGEBLUP_create_Z_sparse_cpp(SEXP factor_idxSEXP, SEXP n_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type factor_idx(factor_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_levels(n_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_Z_sparse_cpp(factor_idx, n_levels));
    return rcpp_result_gen;
END_RCPP
}
// compute_ZKZt_cpp
arma::mat compute_ZKZt_cpp(const arma::mat& Z, const arma::mat& K);
RcppExport SEXP _CompGEBLUP_compute_ZKZt_cpp(SEXP ZSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ZKZt_cpp(Z, K));
    return rcpp_result_gen;
END_RCPP
}
// solve_mme_cpp
Rcpp::List solve_mme_cpp(const arma::vec& y, const arma::mat& X, const arma::mat& Z, const arma::mat& K, double sigma2_g, double sigma2_e);
RcppExport SEXP _CompGEBLUP_solve_mme_cpp(SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP KSEXP, SEXP sigma2_gSEXP, SEXP sigma2_eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_g(sigma2_gSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_e(sigma2_eSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_mme_cpp(y, X, Z, K, sigma2_g, sigma2_e));
    return rcpp_result_gen;
END_RCPP
}
// is_positive_definite_cpp
bool is_positive_definite_cpp(const arma::mat& M, double tol);
RcppExport SEXP _CompGEBLUP_is_positive_definite_cpp(SEXP MSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(is_positive_definite_cpp(M, tol));
    return rcpp_result_gen;
END_RCPP
}
// make_pd_cpp
arma::mat make_pd_cpp(const arma::mat& M, double tol);
RcppExport SEXP _CompGEBLUP_make_pd_cpp(SEXP MSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(make_pd_cpp(M, tol));
    return rcpp_result_gen;
END_RCPP
}
// decode_bed_cpp
IntegerMatrix decode_bed_cpp(RawVector bed_data, int n_ind, int n_snp);
RcppExport SEXP _CompGEBLUP_decode_bed_cpp(SEXP bed_dataSEXP, SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type bed_data(bed_dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(decode_bed_cpp(bed_data, n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// solve_henderson_mme_cpp
Rcpp::List solve_henderson_mme_cpp(const arma::vec& y, const arma::mat& X, const arma::mat& Z, const arma::mat& K_inv, double sigma2_g, double sigma2_e);
RcppExport SEXP _CompGEBLUP_solve_henderson_mme_cpp(SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP K_invSEXP, SEXP sigma2_gSEXP, SEXP sigma2_eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K_inv(K_invSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_g(sigma2_gSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_e(sigma2_eSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_henderson_mme_cpp(y, X, Z, K_inv, sigma2_g, sigma2_e));
    return rcpp_result_gen;
END_RCPP
}
// fit_henderson_mme_cpp
Rcpp::List fit_henderson_mme_cpp(const arma::vec& y, const arma::mat& X, const arma::mat& Z, const arma::mat& K, double sigma2_g_init, double sigma2_e_init, int max_iter, double tol, bool verbose);
RcppExport SEXP _CompGEBLUP_fit_henderson_mme_cpp(SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP KSEXP, SEXP sigma2_g_initSEXP, SEXP sigma2_e_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_g_init(sigma2_g_initSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_e_init(sigma2_e_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_henderson_mme_cpp(y, X, Z, K, sigma2_g_init, sigma2_e_init, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CompGEBLUP_calc_A_matrix_cpp", (DL_FUNC) &_CompGEBLUP_calc_A_matrix_cpp, 1},
    {"_CompGEBLUP_calc_D_matrix_cpp", (DL_FUNC) &_CompGEBLUP_calc_D_matrix_cpp, 1},
    {"_CompGEBLUP_calc_epistatic_matrix_cpp", (DL_FUNC) &_CompGEBLUP_calc_epistatic_matrix_cpp, 2},
    {"_CompGEBLUP_eigen_decomp_cpp", (DL_FUNC) &_CompGEBLUP_eigen_decomp_cpp, 1},
    {"_CompGEBLUP_emma_reml_loglik_cpp", (DL_FUNC) &_CompGEBLUP_emma_reml_loglik_cpp, 4},
    {"_CompGEBLUP_emma_reml_cpp", (DL_FUNC) &_CompGEBLUP_emma_reml_cpp, 5},
    {"_CompGEBLUP_gwas_emmax_cpp", (DL_FUNC) &_CompGEBLUP_gwas_emmax_cpp, 6},
    {"_CompGEBLUP_create_Z_sparse_cpp", (DL_FUNC) &_CompGEBLUP_create_Z_sparse_cpp, 2},
    {"_CompGEBLUP_compute_ZKZt_cpp", (DL_FUNC) &_CompGEBLUP_compute_ZKZt_cpp, 2},
    {"_CompGEBLUP_solve_mme_cpp", (DL_FUNC) &_CompGEBLUP_solve_mme_cpp, 6},
    {"_CompGEBLUP_is_positive_definite_cpp", (DL_FUNC) &_CompGEBLUP_is_positive_definite_cpp, 2},
    {"_CompGEBLUP_make_pd_cpp", (DL_FUNC) &_CompGEBLUP_make_pd_cpp, 2},
    {"_CompGEBLUP_decode_bed_cpp", (DL_FUNC) &_CompGEBLUP_decode_bed_cpp, 3},
    {"_CompGEBLUP_solve_henderson_mme_cpp", (DL_FUNC) &_CompGEBLUP_solve_henderson_mme_cpp, 6},
    {"_CompGEBLUP_fit_henderson_mme_cpp", (DL_FUNC) &_CompGEBLUP_fit_henderson_mme_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_CompGEBLUP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
